
baseURL: 'https://zephnet.biz/'
languageCode: en-us
title: Zephnetdotbiz
theme: himstagram
contentDir: content
publishDir: public
timeZone: 'America/New_York'
buildFuture: true
permalinks:
  singles: '/:title/'
params:
  timeZone: 'America/New_York'
menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Plants
      url: /plants/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
markup:
  highlight:
    style: gruvbox
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
outputs:
  home:
  - html
  - rss
  section:
  - html
  - rss
  taxonomy:
  - html
  term:
  - html
