name = "zephnet"
pages_build_output_dir = "./public"
compatibility_date = "2025-06-26"
[vars]
GH_USERNAME = "zazzyzeph"
REPO = "zephnet"
BRANCH = "main"
POSTS_MD_DIR = "content/posts"
POSTS_PUBLIC_DIR = "public"
HUGO_VERSION = "0.147.9"
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "media"
