# NOTE - for custom domains - change your build command to (example) `hugo -b https://zephnet.biz`. This will override the https://random.pages.dev/ urls. They recommend using $CF_PAGES_URL but that does not work for the generated rss feeds (right now at least! 10-30-2025)

name = "zephnet"
pages_build_output_dir = "./public"
compatibility_date = "2025-06-26"
# pages doesn't support cf workers' error dashboard (yet)
# [observability]
# enabled = true
# head_sampling_rate = 1
[vars]
GH_USERNAME = "zazzyzeph"
REPO = "zephnet"
BRANCH = "main"
POSTS_MD_DIR = "content/posts"
POSTS_PUBLIC_DIR = "public"
HUGO_VERSION = "0.150.0"
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "media"
[[d1_databases]]
binding = "db"
database_name = "zephnet_db"
database_id = "a6482bac-1756-436c-b82b-e53c7f4cdd1a"
